---
parent: central
serviceName: plivo-java
language: java-sdk
build:
  command: |
      export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
      ./gradlew createPom
      ./build.sh
      ./gradlew fatJar
secrets:
  files:
    SONATYPE_SECRING_FILE: "secring.gpg"
postDeployJobs:
  prod:
    - name: plivo/messaging-qa/javaSDKSmoke
      disabled: false
